language: cpp

# This doesn't work - travis defaults to plain gcc if unknown
# http://github.com/travis-ci/travis-ci/issues/979
# http://llvm.org/apt/
compiler:
  - gcc
#  - gcc-4.9
#  - clang-3.4
#  - clang-3.5

os:
  - osx
#cache:
#  - apt

#services:
#  - memcached
#  - redis-server

before_install:
  - brew update 
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  - brew tap mcuadros/homebrew-hhvm
  - brew install freetype gettext cmake git libtool mcrypt oniguruma re2c autoconf libelf readline automake mysql-connector-c pcre gd icu4c libmemcached pkg-config tbb imagemagick binutils curl imap-uw libxslt libevent sqlite homebrew/versions/gcc48 openssl 
  - brew install --build-from-source --cc=gcc-4.9 glog
  #- brew install https://gist.github.com/slbmeh/9059260/raw/1cbf0f6f5639b4a066395bedb702cdd6bd895d15/libdwarf.rb https://gist.github.com/sgolemon/8fdc7e2afcd73a960b9c/raw/1211e21151ed3443dbc027e5383fb49e9eb1ab91/jemallocfb.rb
  
# Commands before installing prerequisites
before_script:
  - time brew install hhvm --with-gcc
# we can't compile with this system version
# - time sudo apt-get remove libsqlite3-dev
#  - time TRAVIS=1 ./configure_generic.sh -DENABLE_COTIRE=ON
# for some tests
#  - time sudo locale-gen de_DE && sudo locale-gen zh_CN.utf8 && sudo locale-gen fr_FR
  - time make -j 6
# mysql configuration for unit-tests
#  - mysql -e 'CREATE DATABASE IF NOT EXISTS hhvm;'
#  - export PDO_MYSQL_TEST_DSN="mysql:host=127.0.0.1;dbname=hhvm"
#  - export PDO_MYSQL_TEST_USER="travis"
#  - export PDO_MYSQL_TEST_PASS=""
# For PHP5 mysqli tests
#  - export MYSQL_TEST_USER="travis"
#  - export MYSQL_TEST_DB="hhvm"
# For redis tests
#  - export REDIS_TEST_HOST="localhost"

# Sadly, travis only gives up 50 minutes to compile and run our tests. The
# compilation machines usually have a bunch of CPUs but very little RAM so gcc
# dies trying to compile some of our files if we do more than -j 6. So, with -j
# 6 that takes ~40 minutes, leaving only 10 minutes to test. The only thing we
# can fit in that time is the quick tests in no-repo mode. So basically this is
# a smoke test (did it compile and not segfault immediately) instead of a real
# test run. Please check out the attached phabricator to your PR for full unit
# test coverage.
env:
  - TEST_RUN_MODE="-m jit       quick"
  - TEST_RUN_MODE="-m interp    quick"

# Main test script
#script: time hphp/hhvm/hhvm hphp/test/run $TEST_RUN_MODE

# Notifications
# The default is to send email on all failures and changed success
# Adding other notifiers (like IRC) does not disable the email one
notifications:
  email: false

matrix:
  fast_finish: true
